### ISSUE TITLE
Should it throw an error if the property is not defined and defaultValue is missing?

### ISSUE THREAD

**Issue by stevemao** [mariocasciaro/object-path#43]
```js
expect(objectPath.get({}, 'deep.notDefined', undefined)).to.equal(undefined);
```
but
```js
try {
  objectPath.get({}, 'deep.notDefined');
} catch (e) {
  assert(e.toString() === 'TypeError: Cannot read property \'notDefined\' of undefined');
}
```

**Comment by mariocasciaro** [comment]
IMO, one of the most useful aspects of object-path is the fact that it is "forgiving", it doesn't throw in case of missing properties. Personally, this is one of the main use cases of the library.

**Comment by stevemao** [comment]
You could make it forgiving by providing a default value. if `objectPath.get(obj, 'deep.notDefined')` returns undefined user might assume that `obj.deep` exists hence there might be a bug.

**Comment by pocesar** [comment]
well, `if (obj.deep.notDefined) { ... }` does that just fine

#30 was looking for something like that

**Comment by pocesar** [comment]
if you expect something to throw synchronously, you just use try/catch and the code you expect to throw. with generators you can safely throw async, but that's not the case. nowadays everyone wants to cut error handling that is a basic and simple task. 

```js
if ((var value = objectPath.get(obj, ['some.deep.path'])) {
   // deal with the value
} else {
  // move along
}
```

no pain and no effort in simple error handling. there's no need to throw there, there's no overhead since you are doing a simple get call and reusing the return if any, you are aware that your object might not be complete (the object might not have some.deep.path defined). and that's it. and that's the way to think ahead. if you can do proper error handling thinking ahead, you shouldn't be worrying about throwing from programming errors.
