### ISSUE TITLE
[Question] What is the use of getKey

### ISSUE THREAD

**Issue by SatanWoo** [mariocasciaro/object-path#57]
After reading your code, I have one confusion about the implementation of getKey
<pre>
function getKey(key){
    var intKey = parseInt(key);
    if (intKey.toString() === key) {
        return intKey;
    }
    return key;
} 
</pre>

Can someone explain a bit ? I mean I know what this function does. But why we have to use getKey to assign the value to something like currentPath as below

<code>
var currentPath = getKey(path[0]);
</code>

**Comment by pocesar** [comment]
it tries to see if the key is a number, if it is, return the number representation instead of the string representation. a path like 'some.0.path' will create the object `{ some: [ { path: 'value' } ] }` instead of `{ some: { 0: { path: 'value' } } }`. it's just to make sure it creates an array instead of an object in case it doesn't exists

**Comment by SatanWoo** [comment]
Got it! Thanks for your apply : )
