### ISSUE TITLE
Dot values in keys?

### ISSUE THREAD

**Issue by souluniversal** [mariocasciaro/object-path#67]
``` javascript
var obj = {
  a: {
    b: "d",
    c: ["e", "f"],
    '\u1200': 'unicode key',
    'dot.dot': 'key'
  },
  "x.y":"doesn't work"
};

objectPath.get(obj, ["x.y"]);

"doesn't work"

objectPath.get(obj, "x.y"); // This one doesn't work, and I would think it should :(
objectPath.get(obj, "a.dot.dot"); // This one doesn't work, and I would think it should :(

```
Can't see any reason why it wouldn't fallback to finding a['dot.dot'] if a.dot.dot is not defined. Am I missing something?

:)

**Comment by pocesar** [comment]
values passed using an array are used as-is, meaning they won't have their values converted from strings to number, or split using the dots. so basically ['a', '0'] isn't the same as ['a', 0] that isn't the same as ['a.0']

**Comment by revelt** [comment]
I think this feature or a bug however you name it should be addressed in readme — namely, use of dots in key names is not allowed. Additionally, dots in object key names is allowed in JSON and it's a problem with `object-path`, this issue is still relevant and should not be closed.

If we are thinking about implementing a bracket notation #96 , this could be the solution — pass key names in a bracket notation like OP and your intent to escape would be understood.
