### ISSUE TITLE
get(global, 'navigator.userAgent') === undefined

### ISSUE THREAD

**Issue by kilianc** [mariocasciaro/object-path#70]
```js
ObjectPath.get(global, 'navigator.userAgent') // undefined

const Navigator = ObjectPath.get(global, 'navigator') // Navigator
ObjectPath.get(Navigator, 'userAgent') // undefined

navigator.userAgent // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 ...
navigator['userAgent'] // Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 ...
```

**Comment by pocesar** [comment]
what variable is `global`? are you in node?

**Comment by kilianc** [comment]
@pocesar `browserify` but it shouldn't matter since `ObjectPath.get(Navigator, 'userAgent')`

**Comment by pocesar** [comment]
version 0.x of objectPath has weird behavior when it come to prototype chain and non-own properties. in version 1.0, there's a switch that you can check for non-own properties.

**Comment by mariocasciaro** [comment]
In 0.11.0 you can now use `objectPath.withInheritedProps.get()`

**Comment by mariocasciaro** [comment]
@pocesar Let me know you thought regarding the new version

**Comment by kilianc** [comment]
@mariocasciaro is there a reason by the behavior of `get(0, 'path')` is different than `o.path` or `o[path]` (aside of `undefined` and `null` handling?)

**Comment by pocesar** [comment]
@mariocasciaro to be honest, I'm a bit disappointed... some time ago we talked about how the new version should look like (API wise), you said no "classes", "state" or anything that can't be used as a singleton. then I redid 1.0.0 to use parameters instead. to extend the existing singleton instead of creating new instances with different behavior, so it could use the same function with a different parameter (ownPropertiesOnly, usually the last param) to access not own properties of the object, since most of the time you'll want to access own properties only. having a noConflict method is something that helps with hacking the library without affecting the singleton. that's what I did with the `extend` function, you can choose to generate a new standalone version of objectPath with plugins, or just a copy of the internal functions for your own delight.

using a singleton member on the objectPath itself with another instance is really wonky, and for JS coders it's breaks the "Principle of least astonishment".

**Comment by kilianc** [comment]
> In 0.11.0 you can now use objectPath.withInheritedProps.get()
I am still confused by this. Why do we need different behavior for ownProps?
