### ISSUE TITLE
An object key starting with a number cannot be deleted using `op.del`

### ISSUE THREAD

**Issue by mellisdesigns** [mariocasciaro/object-path#84]
From what I can see if I have an object key defined as a number, it is unable to be deleted using `op.del`

```
import op from 'object-path';

let users = {
  '12345678': {
    name: 'Mr Bob'
  }
}

op.del(users, 'users.12345678'); // should delete user object
op.get(users, 'users.12345678'); // returns user object

// scenario that works
let cats = {
  'user_12345678': {
    name: 'Mr Meow'
  }
}

op.del(cats, 'user_12345678'); // should delete user object
op.get(cats, 'user_12345678'); // returns undefined as expected
```

I would be happy to take this onboard and try to fix if you are still taking contributions.

**Comment by pocesar** [comment]
not sure if it's a typo, but your path should be `op.del(users, '12345678')`, but that won't work because OP will consider it to be a number, thus will consider the object an array. the only way to be able to work around it is to use an array as path, like so `op.del(users, ['12345678'])`, it won't try to do anything with the keys, will use it as-is

**Comment by mellisdesigns** [comment]
@pocesar that has definitely answered it and I did also have a typo in my code example which I have updated. Thanks for the quick response. Coming from Ember I love this library! Closing issue!
